### PR TITLE
v0.1.1

### PR DESCRIPTION
**Pull request by jethrogb**
Includes #1 and #2 . A `cargo publish` would be nice too :)

### CODE REVIEW

**Comment by emk** [comment]
Agreed. Will publish shortly, ping if I don't.

**Comment by jethrogb** [comment]
ping

**Comment by jethrogb** [comment]
ping again; a bugfix release for one of my crates is blocked on this

**Comment by jethrogb** [comment]
Published as https://crates.io/crates/alloc_buddy_simple2

**Comment by emk** [comment]
OK, my apologies for the ridiculously slow response here. I finally had some time to look through all my repos and get caught up on pull requests.

This pull request looks really great. Merged.

If you would ever like commit privileges or release privileges for any of the supporting crates, please let me know.

**Pull request merged**
